twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        product_image_directory: '%app.product_image_directory_relative_path%'
        shopping_cart: '%app.shopping_cart_storage_key%'
